name: React CI

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest 

    steps: 

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci --production

      - name: Build and test
        run: |
          npm run build
          npm test

      - name: AWS Auth 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::590939892034:role/OIDC_GITHUB_CICD
          role-session-name: S3Deployment

      - name: Deploy to AWS S3
        env:
          AWS3: ${{ secrets.AWS_S3_BUCKET }}
          DIST: build
        run: |
          aws s3 sync --delete ${{ env.DIST }} s3://$AWS3
